
server:
  port: 8083
dubbo:
  application:
    name: item_web
  registry:
    address: zookeeper://192.168.6.128:2181
  consumer:
    check: false
spring:
  rabbitmq:
    host: 192.168.6.128
    username: admin
    password: admin
    virtual-host: /admin
  data:
    solr:
      host: http://198.168.6.128:8080/solr
