
spring:
  thymeleaf:
    cache: false
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://192.168.6.128:2181
  consumer:
    check: false
    timeout: 20000
server:
  ip: 192.168.6.128
fdfs:
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 192.168.6.128:22122