
spring:
  datasource:
    url: jdbc:mysql:///shop2
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    #\u4F7F\u7528Druid\u8FDE\u63A5\u6C60
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 5
      max-active: 100
      max-wait: 60000
      initial-size: 5
      #\u914D\u7F6Edruid\u7684\u76D1\u63A7\u4E2D\u5FC3
      stat-view-servlet:
        #\u5F00\u542F
        enabled: true
        #\u76D1\u63A7\u4E2D\u5FC3\u8BBF\u95EE\u7684url
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        #\u767D\u540D\u5355
        allow: 127.0.0.1
        #\u9ED1\u540D\u5355.\u4E8C\u8005\u540C\u65F6\u5B58\u5728\uFF0C\u9ED1\u540D\u5355\u4F18\u5148\u7EA7\u66F4\u9AD8
        #deny:
      web-stat-filter:
        enabled: true
        url-pattern: /*
  rabbitmq:
    host: 192.168.6.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /admin
dubbo:
  application:
    name: goods_service
  registry:
    address: zookeeper://192.168.6.128:2181
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false
    timeout: 20000
  provider:
    timeout: 20000
server:
  port: 9090
